# Generated by Django 3.0 on 2026-03-10 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=100)),
                ('Time', models.CharField(max_length=100)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phonenumber', models.BigIntegerField()),
                ('photo', models.CharField(max_length=300)),
                ('qualification', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('proof', models.CharField(max_length=300)),
                ('AUTHUSER', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phonenumber', models.BigIntegerField()),
                ('AUTHUSER', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduledate', models.CharField(max_length=100)),
                ('fromtime', models.CharField(default='6:00', max_length=100)),
                ('totime', models.CharField(default='7:00', max_length=100)),
                ('EXPERT', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.Expert')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('EXPERT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Expert')),
                ('PATIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prediction', models.CharField(max_length=100)),
                ('Filepath1', models.CharField(max_length=100)),
                ('Filepath2', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('APPOINTMENT', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('complaint', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('EXPERT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Expert')),
                ('PATIENT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('EXPERT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fromid', to='myapp.Expert')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Toid', to='myapp.Patient')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='PATIENT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='SCHEDULE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Schedule'),
        ),
    ]
