# Generated by Django 3.0 on 2026-03-10 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='EXPERT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Expert'),
        ),
    ]
