# Generated by Django 3.0 on 2026-03-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20260310_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education_content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fpath', models.CharField(max_length=5000)),
                ('title', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=100)),
            ],
        ),
    ]
